version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:80
    environment:
      DB_HOST: database.local
      DB_NAME: reinte33_payment
      DB_USER: reinte33_payment_user
      DB_PASSWORD: GanheComSorteEGanheBem@!3r22234

      PRODUCT_NAME: Serviço De Hospedagem
      PRODUCT_PRICE: 10.30
      PRODUCT_MAX_INSTALLMENTES: 1
      PRODUCT_SALE: "true"

      ASSAS_API: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjRiN2JiYzk4LTg0ZjUtNDVlMS1hZTU1LTFlODBkZGE1NDk0Yzo6JGFhY2hfZTNkMmU5YTctYmVmYS00MmNkLTgwMTgtMDliZTIxZmIzYTZi
      ASSAS_ENV: homologacao

      PRODUCT_MAIL_COMMERCIAL_SMTP:
      PRODUCT_MAIL_COMMERCIAL:
      PRODUCT_MAIL_COMMERCIAL_PASS:
    depends_on:
      - database.local
  database.local:
    image: mariadb:10.5.19
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: GanheComSorteEGanheBem@!3r22234
      MYSQL_DATABASE: reinte33_payment
      MYSQL_USER: reinte33_payment_user
      MYSQL_PASSWORD: GanheComSorteEGanheBem@!3r22234
      MYSQL_MAX_CONNECTIONS: 9000
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./database:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/dump.sql


